function init(self)
	msg.post("player", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if (action_id == hash("fire") or action_id == hash("touch")) and action.pressed then
		local bullet = factory.create("#bulletfactory")
		local pos = go.get_position()
		local to = pos + vmath.vector3(1200, -1000, 0)
		go.animate(bullet, "position", go.PLAYBACK_ONCE_FORWARD, to, go.EASING_INSINE, 0.7, 0, function()
			go.delete(bullet)
		end)
	end
end
