function init(self)
	go.animate(".", "position.y", go.PLAYBACK_LOOP_PINGPONG, 10, go.EASING_INOUTQUAD, 2)
	go.set("#sprite", "tint.w", 0)
	go.animate("#sprite", "tint.w", go.PLAYBACK_ONCE_FORWARD, 1, go.EASING_OUTQUAD, 1)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") and message.other_group == hash("enemy") then
		msg.post("projectx:/projectx", "reset_level")
	end
end
